### ISSUE TITLE
UMD

### ISSUE THREAD

**Issue by jcubic** [11ways/json-dry#1]
In Order to use you library from upkg.com in script tag you need to include

```
<script>
  exports = Dry = {};
</script>
```

it would be nice if you'll included UMD module for browser usage as well for node.

**Comment by skerit** [comment]
I'll check it out. Maybe add a separate dist folder or so?

**Comment by jcubic** [comment]
I've tried to use your library in codepen and I was need to use code like this:
```javascript
exports = Dry = {};
var script = document.createElement('script');
script.src = 'https://rawgit.com/skerit/json-dry/master/lib/json-dry.js';
document.head.appendChild(script);
script.onload =function() {
  Dry.registerClass(Pair);
  Dry.registerClass(Nil);
};
```

UMD would help, you can take look at my [fork](https://github.com/jcubic/json-dry/blob/master/lib/json-dry.js), I can create PR if you want.
